package main;

import core.SecurityBot;
import alert.AlertSystem;
import service.RealTimeMonitor;
import database.DatabaseConnection;

/**
 * Main — Entry point for the AI Security IDS system.
 *
 * Startup sequence:
 *   1. Test MySQL database connection
 *   2. Create shared SecurityBot + AlertSystem instances
 *   3. Start RealTimeMonitor (daemon thread — scans logs every 3s)
 *   4. Start ApiServer (port 8080 — serves the frontend)
 *
 * NOTE: LogGenerator has been REMOVED (BUG 9 fix).
 * Logs are now generated exclusively by Red Team FE via:
 *   POST /api/attack/bruteforce  → inserts LOGIN_FAIL log
 *   POST /api/attack/flood       → inserts REQUEST log
 * This makes the demo realistic: only real attack actions create log entries.
 *
 * If MySQL is unavailable, the system falls back to reading from the text file.
 */
public class Main {
    public static void main(String[] args) {

        System.out.println("============================================");
        System.out.println("   AI Security IDS - Starting up");
        System.out.println("============================================");

        try {
            // STEP 1: Check MySQL connection
            System.out.println("\n[Step 1] Testing MySQL connection...");
            boolean dbOk = DatabaseConnection.testConnection();

            if (!dbOk) {
                System.out.println("   MySQL unavailable -> Using text file as data source");
                System.out.println("   To enable MySQL: run database/setup.sql and add the JDBC driver");
            }

            // STEP 2: Create shared instances
            System.out.println("\n[Step 2] Initializing SecurityBot + AlertSystem...");
            SecurityBot bot = new SecurityBot();
            AlertSystem alertSystem = new AlertSystem();
            System.out.println("   SecurityBot + AlertSystem ready");

            // STEP 3: Start RealTimeMonitor
            System.out.println("\n[Step 3] Starting RealTimeMonitor...");
            RealTimeMonitor monitor = new RealTimeMonitor(bot, alertSystem);
            Thread monitorThread = new Thread(monitor, "RealTimeMonitor-Thread");
            monitorThread.setDaemon(true);
            monitorThread.start();
            System.out.println("   RealTimeMonitor started (scan interval: 3s)");

            // STEP 4: Start API Server
            System.out.println("\n[Step 4] Starting API Server...");
            ApiServer.startServer(bot, alertSystem);

            // Summary
            System.out.println("\n============================================");
            System.out.println("   SYSTEM READY");
            System.out.println("   API:      http://localhost:8080");
            System.out.println("   Database: " + (dbOk ? "MySQL (connected)" : "File text (fallback)"));
            System.out.println("   Blue FE:  Open frontend/dashboard.html");
            System.out.println("   Red FE:   Open frontend/redteam FE/reddash.html");
            System.out.println("   Logs are generated by Red Team attack actions (no auto-generator)");
            System.out.println("============================================\n");

        } catch (Exception e) {
            System.err.println("[Main] Startup error: " + e.getMessage());
            e.printStackTrace();
        }
    }
}